### ISSUE TITLE
SimpleDequePool not getting drained

### ISSUE THREAD

**Issue by daanishsarguru** [reactor/reactor-pool#106]
I have a Spring Boot project which uses **reactor-netty** for **WebClient** which is dependent on **reactor-pool**. I'm using WebClient to make API calls. I'm facing an issue wherein Webclient is not able to create new connections for the incoming requests. All requests for connections from the Pool are added to the Pending Queue and soon enough the Pending Queue becomes full (10000 is the max-queue-size in our case) after which all requests fail with a **PoolAcquirePendingLimitException**

Graph for the Pool Metrics:
![WebclientMetrics](https://user-images.githubusercontent.com/17493538/96625291-9c325d80-132b-11eb-8d3c-97ca2e2866bb.png)

## Expected Behavior
Queue draining should never be failing in any condition

## Actual Behavior
The Queue is not getting drained and remains full

## Steps to Reproduce
Unfortunately, I haven't been able to reproduce this on my local machine. I've only been able to witness this on the production environment randomly in 10% of the running instances
If this helps in any manner, just before this issue occurring, a huge number of `ConnectionExceptions` occur

## Possible Problem
After some investigation, I found something that might be possibly causing this issue
Please note that I wasn't able to reproduce the scenario I've written below

From what I understand from the source code for `SimpleDequePool.java`, new requests called borrowers are added to the `pending` queue and next a call to `drain()` the `pending` queue is made
Before actually draining (`drainLoop()`) the queue, `WIP` is incremented. 
`drainLoop()` is responsible for handling the borrower as well as other borrowers which may have just incremented `WIP` while checking the `(WIP.getAndIncrement(this) == 0)` condition and then decrementing `WIP` for itself as well the other borrowers.
This is because for a single `drainLoop()` call, we don't break out of the infinite loop, until and unless `WIP.decrementAndGet(this) == 0`

If for whatever reason, a call to `drainLoop()` fails to handle decrementing `WIP`, the further requests to `drain()` will never pass the below `if` condition, and the borrowers will just be kept adding to the `pending` queue without ever getting handled
```
void drain() {
    if (WIP.getAndIncrement(this) == 0) {
        drainLoop();
    }
}
```
The fact that the metrics show pending connections = 10000, and no active connections makes me believe this is the condition causing the issue

## Environment
* Reactor version(s) used:
1. reactor-netty: 0.9.12.RELEASE
2. reactor-pool: 0.1.6.RELEASE
* Spring Boot: 2.2.10.RELEASE
* JVM version: openjdk version "1.8.0_181"
* OS and version: alpine:3.6

**Comment by simonbasle** [comment]
Would you be able to test with `reactor-netty` `0.9.13.BUILD-SNAPSHOT` ? it should embed pool `0.1.7.BUILD-SNAPSHOT` which might have a fix related to this.

**Comment by daanishsarguru** [comment]
@simonbasle Thanks for the quick reply. Sure, will give the snapshot a try. Will test this for a week and let you know

**Comment by simonbasle** [comment]
FYI we're planning to release 0.1.7 next monday

**Comment by daanishsarguru** [comment]
@simonbasle Looks like the issue is resolved. Haven't seen it occurring since upgrading to **reactor-netty 0.9.13.RELEASE**. Thanks for the help 👍

**Comment by simonbasle** [comment]
thanks for confirming, great that the latest release resolved that issue as well 👍
