### ISSUE TITLE
dependency to reactor-core should be api instead of implementation

### ISSUE THREAD

**Issue by ericbottard** [reactor/reactor-pool#107]
This translated to runtime in maven POM instead of compile.

**Comment by violetagg** [comment]
@ericbottard Does this mean that reactor pool can run with whatever version is reactor-core?
Does this mean that if an API is deprecated in reactor core, reactor pool will continue to use this deprecated API so that it can run with every version of reactor core?

**Comment by ericbottard** [comment]
> Does this mean that reactor pool can run with whatever version is reactor-core?

no

> Does this mean that if an API is deprecated in reactor core, reactor pool will continue to use this deprecated API 

I don't know

This issue is about the fact that reactor-core types leak in the signatures of reactor-pool, so should be marked API, not implementation (which in practice doesn't change mush because of course some project using r-pool uses reactor-core, but this is to be 100% correct)

**Comment by simonbasle** [comment]
(to clarify, currently `runtime` scope is produced in the pom, this change will turn that into `compile` scope in the pom)
