### ISSUE TITLE
Missing SimpleDequePool.drain() when SimpleDequePool.cancelAcquire()

### ISSUE THREAD

**Issue by andreisilviudragnea** [reactor/reactor-pool#127]
When a pending acquire is cancelled, the loop should be drained so other pending acquires can be served.

## Steps to Reproduce

https://github.com/andreisilviudragnea/project-reactor-bugs/blob/master/src/test/java/com/example/MissingDrainLoopOnCancelBugTest.java
```java
public class MissingDrainLoopOnCancelBugTest {

	private final InstrumentedPool<String> stringReactivePool = PoolBuilder
			.from(Mono.just("value").delayElement(Duration.ofMinutes(10)))
			.maxPendingAcquireUnbounded()
			.sizeBetween(0, 1)
			.buildPool();

	@Test
	public void missingDrainLoopOnCancelBug() {
		InstrumentedPool.PoolMetrics metrics = stringReactivePool.metrics();

		AtomicReference<Subscription> subscriptionReference = new AtomicReference<>();

		AtomicBoolean next1 = new AtomicBoolean();

		stringReactivePool.acquire().subscribe(
				stringPooledRef -> next1.set(true),
				throwable -> System.out.println("error1"),
				() -> System.out.println("complete1"),
				subscription -> {
					subscriptionReference.set(subscription);
					subscription.request(Long.MAX_VALUE);
				}
		);

		assertFalse(next1.get());

		AtomicBoolean next2 = new AtomicBoolean();

		stringReactivePool.acquire().subscribe(
				stringPooledRef -> next2.set(true),
				throwable -> System.out.println("error2"),
				() -> System.out.println("complete2")
		);

		assertFalse(next1.get());
		assertFalse(next2.get());

		System.out.println("before cancel");

		subscriptionReference.get().cancel();

		assertFalse(next1.get());
		assertFalse(next2.get()); // should be true

		System.out.println("after cancel");

		assertEquals(metrics.acquiredSize(), 1); // should be 0 for current implementation, given that no acquire is successful
		assertEquals(metrics.pendingAcquireSize(), 1); // should be 0
	}
}
```

## Your Environment

* Reactor version(s) used: `reactor-core:3.4.4`, `reactor-pool:0.2.3`
* JVM version (`java -version`):
```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (Zulu 8.52.0.23-CA-linux64) (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (Zulu 8.52.0.23-CA-linux64) (build 25.282-b08, mixed mode)
```
* OS and version (eg `uname -a`):
```
Linux andrei-desktop 5.8.0-45-generic #51-Ubuntu SMP Fri Feb 19 13:24:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by simonbasle** [comment]
That test seem wrong. How can _any_ `onNext` happen at the level of the `next2.get()` assertion if the allocator delays emission of the resource by 10 minutes??

Note that currently one limitation of the pool is that once an _allocation_ is triggered, is won't receive cancellation signals.
In the drain loop it is also eagerly connected with a `Borrower`, which is the `Subscription` that can be cancelled here.

So cancelling an acquire Mono would effectively still let the allocator run its full course, and then the resource would get `released()` [upon reaching the `Borrower`](https://github.com/reactor/reactor-pool/blob/68e3453b70e0b3ed5f0a8daf4d22c7ac2c3685ed/src/main/java/reactor/pool/AbstractPool.java#L415). That does trigger the `drain()` loop so if there is another pending borrower, the resource is already available.
