### ISSUE TITLE
Constantly keeping 10 idle connections

### ISSUE THREAD

**Issue by petromir** [reactor/reactor-pool#136]
During investigation of https://github.com/r2dbc/r2dbc-pool/issues/115 I've noticed that there are idle connections which are never closed. I've created a repository which can be used to reproduce the issue https://github.com/petromir/r2dbc-pool-idle-connection-issue. Note that even if the maximum size of the pool is 2, we will always have 10 open idle connections to the database.

## Expected Behavior
When the application doesn't have any activity, it shouldn't use database resources.

## Actual Behavior
We always have 10 open idle connections to the database with initial query of `SELECT oid, typname FROM pg_catalog.pg_type WHERE typname IN ('hstore')`

## Steps to Reproduce
Use https://github.com/petromir/r2dbc-pool-idle-connection-issue

## Possible Solution
Provide an option to set the amount of connection kept in the background, e.g. `maxIdleConnections`.

## Your Environment

* r2dbc-pool - 0.9.0.M1
* r2dbc-postgresql - 0.8.7.RELEASE
* reactor-pool - 0.2.2
* reactor-core - 3.4.3
* Database: PostgreSQL 11.4
* JVM version: 1.8.0.202
* OS and version: macOS Big Sur 11.3 / Google Cloud Plaform

**Comment by simonbasle** [comment]
@petromir as discussed in the r2dbc-pool issue, without activity on the pool you need background eviction enabled for it to dispose of idle objects that don't pass the eviction predicate anymore. so this needs to be implemented in `r2dbc-pool` directly (which should be easy to contribute).

**Comment by petromir** [comment]
Well using background eviction doesn't help to close the actual connection, just making pool statistics look right.

The issue is easy to reproduce:
1. Clone my version of [r2dbc-pool](https://github.com/petromir/r2dbc-pool) with added support for background eviction. 
2. Run `mvn clean install -DskipTests`
3. Clone https://github.com/petromir/r2dbc-pool-idle-connection-issue and follow the steps defined in the repository.

As a result we have JMX statistics looking good (with 0 idle connection), BUT still 10 database connections in idle state.
```sql
select state, count(pid), query FROM pg_stat_activity where datname = 'books' and pid<>pg_backend_pid() and application_name = 'r2dbc-postgresql' group by state, query;
```
|state|count|query|
|-----|-----|-----|
|idle|10|INSERT INTO book (title, author) VALUES ($1, $2) RETURNING *|

Am I missing something?  

I've noticed that there is `.releaseHandler(Connection::close)` which results in two exceptions

- `Caused by: java.lang.IllegalStateException: The connection is closed`
This seems to be `r2dbc-pool` specific as we have assertion whether `io.r2dbc.pool.PooledConnection` is closed in several places
```java
private void assertNotClosed() {
        if (this.closed) {
            throw new IllegalStateException("The connection is closed");
        }
}
```
- Inability to acquire a connection.
```java
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 7000ms in 'Connection Acquisition from [ConnectionPool[PostgreSQL]]' (and no fallback has been configured)
```

**Comment by simonbasle** [comment]
I see that in your fork you've enabled background eviction but also switched from a `releaseHandler` to a `destroyHandler` for `Connection::close`. Can you confirm that if `assertNotClosed` exception is caught and turned into a `Mono.error` in that `destroyHandler` function, it improves the situation?

**Comment by simonbasle** [comment]
(there might indeed be an issue with `destroyHandler`s that throw from the `Function` instead of returning a `Mono.error`. reopening)

**Comment by petromir** [comment]
@simonbasle The only thing that I have done in my version is adding of `.evictInBackground(maxIdleTime)` during pool construction. See [original version](https://github.com/r2dbc/r2dbc-pool/blob/main/src/main/java/io/r2dbc/pool/ConnectionPool.java#L206) vs. [mine](https://github.com/petromir/r2dbc-pool/blob/6a50061368c04d87c5e5b7eac96ec69e1e97564e/src/main/java/io/r2dbc/pool/ConnectionPool.java#L208)
It will take a bit more time until I convert all the invocations of `assertNotClosed` to `Mono<Void>`.

**Comment by simonbasle** [comment]
would you be instead able to build reactor-pool from [`136-failingReleaseOrDestroyHandlers` branch](https://github.com/reactor/reactor-pool/tree/136-failingReleaseOrDestroyHandlers) and then your r2dbc-pool fork and validate it fixes your reproduction case?

**Comment by simonbasle** [comment]
@petromir Can you verify latest snapshots (from the merge of #139) with your r2dbc-pool fork and validate it fixes your reproduction case?

**Comment by petromir** [comment]
@simonbasle when 0.2.5 will be available in Maven Central?

**Comment by simonbasle** [comment]
> @simonbasle when `0.2.5` will be available in Maven Central?

Next tuesday (updated the milestones). If you could verify the fix using snapshots today, that would be perfect.

**Comment by petromir** [comment]
I will do my best 😄

**Comment by simonbasle** [comment]
I had some time to investigate, and despite the changes I've made I was still seeing 10 idle connections... Then something felt off, so I tried playing around with the configuration of the pool in the app.

I've set the maximum size to `5` and wrapping the `ConnectionFactory` so that `create()` calls could be counted. And indeed, the _application_ makes less than 5 calls to `create()`...

But still, pg tells me that there are 10 idle connections 🤔

And then I noticed that `ConnectionPoolConfiguration#build` from r2dbc-pool is called twice... and the first time it uses default values for `minSize` and `maxSize`, which happens to be 10 !

So it hit me: you're configuring a pool around a pool:

```java
final ConnectionFactory connectionFactory = ConnectionFactories.get(ConnectionFactoryOptions.builder()
                .option(DRIVER, "pool")
                .option(PROTOCOL, "postgresql")
```

The logs even plainly warn you about it at the start of the application !! 🤦‍♂️ 

> WARN 53028 --- [           main] io.r2dbc.pool.ConnectionPool             : Creating ConnectionPool using another ConnectionPool [ConnectionPool[PostgreSQL]] as ConnectionFactory

Using the postgresql driver directly as basis for the r2dbc-pool, with background eviction, correctly makes these idle connections disappear from pg's perspective.

**Comment by petromir** [comment]
Didn't get what is wrong with the pool configuration as the example in [r2dbc-pool](https://github.com/r2dbc/r2dbc-pool) was used as a source
```
ConnectionFactory connectionFactory = ConnectionFactories.get(ConnectionFactoryOptions.builder()
   .option(DRIVER, "pool")
   .option(PROTOCOL, "postgresql") // driver identifier, PROTOCOL is delegated as DRIVER by the pool.
   .option(HOST, "…")
   .option(PORT, "…") 
   .option(USER, "…")
   .option(PASSWORD, "…")
   .option(DATABASE, "…")
   .build());
```

**Comment by petromir** [comment]
Well this seems to be quite confusing for users of `r2dbc-pool` as configuring the pool programmatically is exactly in the way I did it
```java
ConnectionFactory connectionFactory = …;

ConnectionPoolConfiguration configuration = ConnectionPoolConfiguration.builder(connectionFactory)
   .maxIdleTime(Duration.ofMillis(1000))
   .maxSize(20)
   .build();

ConnectionPool pool = new ConnectionPool(configuration);
```
What should be the right way to combine both settings, so that we don't have several connection pools created?

**Comment by petromir** [comment]
And then I can safely call `ConnectionPool pool = new ConnectionPool(configuration);`
