### ISSUE TITLE
Wrong pool metrics when invalidating an idle resource

### ISSUE THREAD

**Issue by violetagg** [reactor/reactor-pool#146]
## Expected Behavior
Invalidating an idle resource decreases the idle and allocated counters and does not touch acquired counter

## Actual Behavior
Invalidating an idle resource decreases the acquired counter and does not affect idle and allocated counters

## Steps to Reproduce
```
	@ParameterizedTestWithName
	@MethodSource("allPools")
	void testInvalidateAfterReleaseMetrics(Function<PoolBuilder<PoolableTest, ?>, Pool<PoolableTest>> configAdjuster) {
		PoolBuilder<PoolableTest, ?> builder = PoolBuilder
				.from(Mono.fromCallable(() -> new PoolableTest(1)))
				.sizeBetween(0, 1);

		final Pool<PoolableTest> pool = configAdjuster.apply(builder);
		assertThat(pool).isInstanceOf(InstrumentedPool.class);
		@SuppressWarnings("rawtypes")
		final PoolMetrics metrics = ((InstrumentedPool) pool).metrics();

		final PooledRef<PoolableTest> ref1 = pool.acquire().block();

		assertThat(ref1).isNotNull();
		assertThat(metrics.acquiredSize()).as("initial acquired").isEqualTo(1);
		assertThat(metrics.allocatedSize()).as("initial allocated").isEqualTo(1);
		assertThat(metrics.idleSize()).as("initial idle").isEqualTo(0);

		ref1.release().block();

		assertThat(metrics.acquiredSize()).as("1 release: acquired").isEqualTo(0);
		assertThat(metrics.allocatedSize()).as("1 release: allocated").isEqualTo(1);
		assertThat(metrics.idleSize()).as("1 release: idle").isEqualTo(1);

		ref1.invalidate().block();

		assertThat(metrics.acquiredSize()).as("1 invalidate: acquired").isEqualTo(0);
		assertThat(metrics.allocatedSize()).as("1 invalidate: allocated").isEqualTo(0);
		assertThat(metrics.idleSize()).as("1 invalidate: idle").isEqualTo(0);
	}
```

**Comment by simonbasle** [comment]
it definitely shouldn't decrease the `acquired` counter, and that by itself is a bug.

however, I don't know if it should be allowed to `invalidate()` at all in this case. if the resource is idle/has been released, it means the caller has relinquished control of the resource back to the pool. further `release()` and `invalidate()` calls should be no-op at that point, shouldn't they?

**Comment by violetagg** [comment]
@simonbasle let say that you use a connection for a given request (HTTP) then you return this connection to the pool, meanwhile the connection is closed. If we cannot invalidate the resource as it is not usable anymore, the resource will stay in the pool until there is an acquire operation that will remove it from the pool, however that acquire operation may happen at any time in the next seconds or the next hour.

**Comment by simonbasle** [comment]
Yeah I understand, but that's why we added background eviction.

From a glance at the codebase, the assumption that `invalidate()` is NO-OP after `release()` is there throughout the code. You shouldn't hold to a `PooledRef` after having called either of its `release()` and `invalidate()` method.

That is a far wider change with potential breaking implications 😞

**Comment by violetagg** [comment]
yeah, closing
