### ISSUE TITLE
when I use spring cloud gataway，I find reactor.netty.internal.shaded.reactor.pool.AbstractPool.Borrower#request use a lot of cpu

### ISSUE THREAD

**Issue by yanwenliang** [reactor/reactor-pool#160]
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/7390709/183856339-aed5637e-fe2c-4b34-944e-8746490e5490.png">

```
reactor.netty.internal.shaded.reactor.pool.AbstractPool.Borrower#request

boolean noIdle = this.pool.idleSize() == 0; 

public int idleSize() {
    Queue<?> e = (Queue)IDLE_RESOURCES.get(this);
    return e == null ? 0 : e.size();
}
```
why don't use isEmpty() replace size(). 
java.util.concurrent.ConcurrentLinkedDeque#size use more than 15% cpu

**Comment by violetagg** [comment]
@yanwenliang This has been fixed. See #155
