### ISSUE TITLE
Add support to pool to do scheduled connection validation

### ISSUE THREAD

**Issue by ifindya** [reactor/reactor-pool#169]
Provide the kind of functionality that the connection validation is periodically run in the background.

## Motivation

Typically, idle connections will become invalid due to timeouts, network side, or the other cause, in which case we potentially would have to retry the acquirement of the whole pool size of connections when performing a database call and it would be even worse if no valid connections exist which would result to re-warmup the pool.  That can significantly increase the time of database calls, which could have been avoided if the connection validation was periodically run in the background.
## Desired solution

Checking for each connection periodically if it has exceeded its saying maxIdleTime, also check for each connection whether it is valid or not. Also, after the checks, the connection pool should be re-warmuped, so that it contains at least minIdle connections. Some popular libraries like HikariCP (keepaliveTime) and C3P0 (idleConnectionTestPeriod) and Druid(keepAlive) have this feature, which could be referenced.

**Comment by violetagg** [comment]
@ifindya There is already such functionality. Can you try this configuration?
https://github.com/reactor/reactor-pool/blob/574c24b3745625263e5dafd209ef6ec3dd30594d/reactor-pool/src/main/java/reactor/pool/PoolBuilder.java#L227-L249

**Comment by ifindya** [comment]
Thank you so much. I have had a look. background tasks are used to evict idle connections and do not keep the connection active, sometimes needing to contain **minIdle** idle connections in the connection pool at all times until the pool shutdown, in other words, idle connections are exempt from eviction. Did I get that right?

**Comment by violetagg** [comment]
@ifindya Yes correct.

For example in Reactor Netty the connection pool has these settings: max idle time, max life time, active/closed connection.
So when the background task is executed these settings are checked and some of the connections might be evicted (removed) from the pool.

If the connection pool supports warm up then after the eviction of the pool needs to be filled again with fresh connections then this will be performed.

**Comment by violetagg** [comment]
> @violetagg That's to say Reactor Pool doesn't have these settings and might not warm up after the eviction, right? If so, is there a plan about supporting this?

On the contrary - everything as infrastructure/configurations is there, the library that **uses** Reactor Pool needs to use/configure them.

For example, Reactor Netty configures Reactor Pool like this:
https://github.com/reactor/reactor-netty/blob/61d1315c358e73b5a0c3c3e8ace89917f1a9a2ad/reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java#L489-L491

So if background task is enabled the connections will be checked  for idle time, life time and whether they are closed.

Reactor Netty does not have configuration for warm up, but if the library that **uses** Reactor Pool enables the configuration for warm up then the pool will be filled with fresh resources.

**Comment by ifindya** [comment]
All right, then the implementations should be allowed to extend the background task and determine its behavior. Is there such an ability now?

**Comment by violetagg** [comment]
> All right, then the implementations should be allowed to extend the background task and determine its behavior. Is there such an ability now?

Reactor Pool invokes only the eviction predicate. There is nothing else interesting in the background task.
https://github.com/reactor/reactor-pool/blob/574c24b3745625263e5dafd209ef6ec3dd30594d/reactor-pool/src/main/java/reactor/pool/SimpleDequePool.java#L155

The library that uses Reactor pool needs to provide eviction predicate.
As I see that you linked an issue in R2DBC - this means R2DBC has to provide this eviction predicate.

**Comment by ifindya** [comment]
Got it, thanks.

**Comment by grantas33** [comment]
In r2dbc-pool, when checking whether a connection is valid, a call to the database is made which might take a while. Does reactor-pool ensure that during the eviction check, the pool object (in this case, r2dbc connection) which is being checked for eviction will not be used concurrently? Also, how to enable the configuration for warmup?

**Comment by violetagg** [comment]
> In r2dbc-pool, when checking whether a connection is valid, a call to the database is made which might take a while. Does reactor-pool ensure that during the eviction check, the pool object (in this case, r2dbc connection) which is being checked for eviction will not be used concurrently by the pool? 

yes

> Also, how to enable the configuration for warmup?

https://github.com/reactor/reactor-pool/blob/574c24b3745625263e5dafd209ef6ec3dd30594d/reactor-pool/src/main/java/reactor/pool/PoolBuilder.java#L346-L362

**Comment by ifindya** [comment]
> @ifindya Yes correct.
> 
> For example in Reactor Netty the connection pool has these settings: max idle time, max life time, active/closed connection. So when the background task is executed these settings are checked and some of the connections might be evicted (removed) from the pool.
> 
> If the connection pool supports warm up then after the eviction, if the pool needs to be filled again with fresh connections then this will be performed.

I am sorry we're not on the same page before. The library depends on Reactor pool uses eviction predicate to check connection is valid, sometimes connection validation might be a remote call(saying to send a message to server side) in non-block way and BiPredicate is uncompatibility. It seems that there is only one way that will be performed after the eviction is to provide DestoryHandler, which allows users to have effects on the pool from the outside. Therefore, it's not exactly a walk in the park to combine background eviction and warm up. Thanks for your reply in advance.

**Comment by ifindya** [comment]
> @ifindya Yes correct.
> 
> For example in Reactor Netty the connection pool has these settings: max idle time, max life time, active/closed connection. So when the background task is executed these settings are checked and some of the connections might be evicted (removed) from the pool.
> 
> If the connection pool supports warm up then after the eviction, if the pool needs to be filled again with fresh connections then this will be performed.


I am sorry we're not on the same page before. The library depends on Reactor pool uses eviction predicate to check whether connection is valid and that would require obtaining the connection from the pool, testing it, and removing it from the pool if invalid, thus connection validation might be a remote call(saying to send a message to server side) in non-block way and BiPredicate is incompatible. It seems that there is only one way that will be performed after the eviction is to provide DestoryHandler, which allows users to have effects on the pool from the outside. Therefore, it's not exactly a walk in the park to combine background eviction and warm up. Thanks for your reply in advance.
