### ISSUE TITLE
InstrumentedPool.PoolMetrics isInactiveForMoreThan mixes time units

### ISSUE THREAD

**Issue by freelon** [reactor/reactor-pool#176]
The `default boolean InstrumentedPool.PoolMetrics.isInactiveForMoreThan(Duration duration);` implementation compares the _seconds_ since the last interaction with the _milliseconds_ of the provided duration.

## Expected Behavior
I would expect the method to return `true` iff the last interaction was longer ago than the provided `duration`.

## Actual Behavior
The method returns `true` iff the last interaction is longer ago than the provided `duration * 1000`, basically.

## Steps to Reproduce

```java
@Test
void reproCase() {

        long inactiveSeconds = 5;
        var metrics = new InstrumentedPool.PoolMetrics() {

            @Override
            public int acquiredSize() {
                return 0;
            }

            @Override
            public int allocatedSize() {
                return 0;
            }

            @Override
            public int idleSize() {
                return 0;
            }

            @Override
            public int pendingAcquireSize() {
                return 0;
            }

            @Override
            public long secondsSinceLastInteraction() {
                return inactiveSeconds;
            }

            @Override
            public int getMaxAllocatedSize() {
                return 0;
            }

            @Override
            public int getMaxPendingAcquireSize() {
                return 0;
            }
        };
        
        assertTrue(metrics.isInactiveForMoreThan(Duration.ofSeconds(1)));
}
```

## Possible Solution

Change `this.secondsSinceLastInteraction() >= duration.toMillis()` to `this.secondsSinceLastInteraction() >= Math.ceil((double) duration.toMillis() / 1000)`.

## Your Environment

* Reactor version(s) used: `main` branch
* Other relevant libraries versions (eg. `netty`, ...): ---
* JVM version (`java -version`): ---
* OS and version (eg `uname -a`): ---

**Comment by violetagg** [comment]
@freelon Yes you are right. When I fixed the actual implementation I forgot to fix the default #137. Would you like to provide a PR?

**Comment by freelon** [comment]
@violetagg yep, I can do that. What source branch should I pick?

**Comment by violetagg** [comment]
> @violetagg yep, I can do that. What source branch should I pick?

Please let's start with `0.2.x` and then we will forward merge the change to `main`
