### ISSUE TITLE
Warmup procedure fails if warmups were found

### ISSUE THREAD

**Issue by kprzybylo** [reactor/reactor-pool#180]
## Expected Behavior
When a warmup method is run, but no warmups to run were found it should not do anything.

## Actual Behavior
When a warmup method is run, but no warmups to run were found SimpleDequePool picks mergeConcurrency as lowest number of configured warmupParallelism and length of found warmups. Found warmups is 0, thus this values is passed further to Flux.merge and results in error from FluxFlatMap.
`java.lang.IllegalArgumentException: maxConcurrency > 0 required but it was 0`

## Steps to Reproduce
We have configured scheduled warmup with our custom find out idle timeout that caused pool to increase our response time. Thus we are running warmup once per X second, but it's not always needed as in high traffic this just simply should be ignored. First run after app starts is fine as then maxConcurrency is 1, but later it's mostly 0 and we just have constant errors.

## Possible Solution
Add check before executing warmups if there is anything to run to avoid unnecessary call for warmup with invalid configuration.

## Your Environment
Spring Boot 3 App with Netty server and reactor-pool 1.0.3.

* Reactor version(s) used: 1.0.3
* Other relevant libraries versions (eg. `netty`, ...): netty, Spring Boot 3
* JVM version (`java -version`): 17

**Comment by kprzybylo** [comment]
Looking at branch 0.1.x seems it might be resolved, but I can't update reactor-pool to higher version to confirm that (parent library limitation). At this moment we are catching and ignoring this exception.

**Comment by pderop** [comment]
@kprzybylo ,

thanks for reporting, this is a regression from #171, only for 1.0.x branch, originating from 1.0.1 version.
There is this ongoing PR which is addressing the problem: #181
