### ISSUE TITLE
Provide methods to retrieve current information

### ISSUE THREAD

**Issue by ttddyy** [reactor/reactor-pool#31]
For monitoring purpose, I think these information needs to be retrievable:
- num of currently idle `POOLABLE`
- num of currently acquired(in-use) `POOLABLE`
- num of currently pending requests

Related: https://github.com/r2dbc/r2dbc-pool/issues/4

**Comment by simonbasle** [comment]
@ttddyy this is covered by https://github.com/reactor/reactor-pool/pull/22/files#diff-2e0c236f9607df06f9dccd61b0c49272 so I'll reference this issue in the commit

**Comment by ttddyy** [comment]
Thanks, `InstrumentedPool.PoolMetrics` should work for r2dbc-pool. :)
