### ISSUE TITLE
Document how to emulate async evictionPredicate

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-pool#36]
We could need something to check on acquisition if a resource is healthy (and if not lead to the eviction/destroy lifecycle).

For instance in reactor-netty we check if the connection is still alive before passing it.

**Comment by simonbasle** [comment]
the eviction Predicate can serve as this, it is applied when releasing a resource but iirc I also started applying it on acquire of an available resource (to be double checked).

**Comment by mp911de** [comment]
Related: r2dbc/r2dbc-mssql#111

In R2DBC, we use a `Mono<Boolean>` to check for connection health in the `releaseHandler` and complete with an error if the connection is not valid.

`Mono<Boolean>` because a driver might issue a query. So having a health checker function is essential for production usage from R2DBC perspective.

**Comment by simonbasle** [comment]
yeah we probably need an async equivalent to the `evictionPredicate`. @mp911de pointed out that the implementation should be separate, in order to avoid wrapping the simple `boolean` case in a `Mono` and adding unnecessary overhead.

**Comment by simonbasle** [comment]
the `evictionPredicate`, which can be seen as the opposite side of the healthcheck coin, is currently invoked in the `drainLoop`... this makes it quite complicated to switch to an async model. @mp911de I wonder if the `PooledRef#invalidate()` method could be used here instead, at the r2dbc-pool level?

The idea would be for r2dbc-pool to:
 1. try `acquire()`
 2. `flatMap` into calling the connection's asynchronous health-check, whatever that is
 3. in case of `false` (or `onError`), `flatMap` into calling `PooledRef#invalidate()` then `acquire` (or replace the acquire with emitting a special `onError` and adding `retry(Class)` to the mix)

**Comment by mp911de** [comment]
That's a decent proposal. Let me try it that way and come back to see how it worked out.

**Comment by simonbasle** [comment]
this needs to be documented, probably?
